# Generated by Django 3.1.6 on 2021-02-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_gallerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
