# Generated by Django 3.1.6 on 2021-02-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_menuitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=25),
        ),
    ]
