# Generated by Django 3.1.6 on 2021-02-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210204_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
