# Generated by Django 3.1.6 on 2021-02-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210205_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
