# Generated by Django 3.1.6 on 2021-02-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_menuitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='quantity',
        ),
    ]
